on:
  workflow_dispatch:
    inputs:
      environment:
        description: "部署环境"
        required: true
        default: "staging"
      reason:
        description: "触发原因"
        required: false

jobs:
  prepare_release:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Get release tag
      id: release_tag
      run: |
        release_tag="FriendlyWrt-$(date +%Y-%m-%d)"
        echo "release_tag=$release_tag" >> $GITHUB_ENV
        echo "release_tag=$release_tag" >> $GITHUB_OUTPUT

    - name: Create empty release
      id: release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.release_tag }}
        draft: false
        prerelease: false
    outputs:
      release_tag: ${{ env.release_tag }}
      upload_url: ${{ steps.release.outputs.upload_url }}

  setup_environment:
    runs-on: ubuntu-22.04
    outputs:
      cache_key: ${{ steps.cache_key.outputs.key }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Generate cache key
      id: cache_key
      run: |
        echo "key=env-cache-$(date +%Y%m%d)-$(sha256sum scripts/install_dependencies.sh | cut -d' ' -f1)" >> $GITHUB_OUTPUT
      
    - name: Cache environment
      id: env_cache
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/bin/repo
          ~/toolchain
        key: ${{ steps.cache_key.outputs.key }}
      
    - name: Install dependencies and repo tool
      if: steps.env_cache.outputs.cache-hit != 'true'
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        # 安装环境依赖
        sudo rm -rf /etc/apt/sources.list.d
        wget https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh
        sed -i -e 's/^apt-get -y install openjdk-8-jdk/# apt-get -y install openjdk-8-jdk/g' install.sh
        sed -i -e 's/^\[ -d fa-toolchain \]/# [ -d fa-toolchain ]/g' install.sh
        sed -i -e 's/^(cat fa-toolchain/# (cat fa-toolchain/g' install.sh
        sed -i -e 's/^(tar xf fa-toolchain/# (tar xf fa-toolchain/g' install.sh
        sudo -E bash ./install.sh
        
        # 安装 repo 工具
        git clone https://github.com/friendlyarm/repo
        sudo cp repo/repo /usr/bin/
        chmod +x /usr/bin/repo
        repo --version  # 验证安装
        
        sudo -E git config --global user.name 'GitHub Actions'
        sudo -E git config --global user.email 'noreply@github.com'
        sudo swapoff -a
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /usr/local/share/boost /opt/ghc
        echo "cores: $(nproc)"

  build_friendlywrt:
    needs: [prepare_release, setup_environment]
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        VERSION: ['24.10']
        SET: [docker]
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Restore environment
      uses: actions/cache@v3
      with:
        path: |
          /usr/local/bin/repo
          ~/toolchain
        key: ${{ needs.setup_environment.outputs.cache_key }}

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        mkdir -p ./artifact
        echo "cores: $(nproc)"

    - name: Download source
      run: |
        mkdir project
        cd project
        repo init --depth=1 -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v${{ matrix.VERSION }} \
                -m rk3568.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle

        repo sync -c friendlywrt --no-clone-bundle
        repo sync -c configs --no-clone-bundle
        repo sync -c device/common --no-clone-bundle
        repo sync -c device/friendlyelec --no-clone-bundle
        repo sync -c scripts --no-clone-bundle
        repo sync -c scripts/sd-fuse --no-clone-bundle
        repo sync -c toolchain --no-clone-bundle

    - name: Apply customizations
      run: |
        cd project
        source ../scripts/add_packages.sh
        source ../scripts/custome_config.sh

    - name: Prepare dot config and feeds
      run: |
        cd project
        SUFFIX="-docker"
        DIRNAME=friendlywrt$(echo ${{ matrix.VERSION }}|awk -F . '{print $1}')${SUFFIX}
        CONFIG=rockchip${SUFFIX}
        cat > .current_config.mk <<EOL
        . device/friendlyelec/rk3568/base.mk
        TARGET_IMAGE_DIRNAME=${DIRNAME}
        TARGET_FRIENDLYWRT_CONFIG=${CONFIG}
        EOL
        DEBUG_DOT_CONFIG=1 ./build.sh friendlywrt

    - name: Download package
      id: download_packages
      run: |
        cd project/friendlywrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile friendlyWrt
      id: compile
      continue-on-error: true
      run: |
        cd project/friendlywrt
 